# Generated by Django 6.0.2 on 2026-03-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, to='appSite.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSite.user'),
        ),
    ]
