# Generated by Django 6.0.2 on 2026-03-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0004_user_library_alter_game_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='purchase_date',
        ),
    ]
