# Generated by Django 6.0.2 on 2026-03-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0005_remove_game_buyer_remove_game_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSite.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSite.user')),
            ],
        ),
    ]
