# Generated by Django 6.0.2 on 2026-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0006_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'game')},
        ),
    ]
